# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: AlgoNws   # An ID to reference
    type: Git
    name: ALGO-NWS          # The name of the repository for the submodule
  - repository: AlgoGos
    type: Git
    name: ALGO-GOS
  - repository: AlgoShared
    type: Git
    name: ALGO-SHARED

trigger: none
# - main

pool:
  vmImage: windows-latest

jobs:
  - job: buildApplication
    displayName: Build Application
    steps:
      - checkout: self
        submodules: true

      # Frontend
      # -------

      - script: |
          (cd src/renderer && npm install && npm run build)
        displayName: 'Build the renderer'

      # Application
      # -------

      - script: npm install
        displayName: NPM install

      # NWS - WIN

      - script: node tools/activate-algo.js algo-uscadi
        displayName: "Activate algorithm 'algo-uscadi'"

      - script: npx electron-forge make --arch=x64 --platform=win32
        displayName: Electron-Forge make

      - script: ls -laR out/
        displayName: Lets look at the output
          
    

    uses:
      repositories:
      - AlgoNws
      - AlgoGos
      - AlgoShared

