# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- checkout: self
  submodules: true

- script: echo 'Build pipeline started'
  displayName: 'Run a one-line script'

- script: npm install
  displayName: 'Run `npm install`'

- script: |
    (cd src/renderer && npm install && npm run build)
  displayName: 'Build the renderer'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
