# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: AlgoNws
    type: Git
    name: ALGO-NWS
  - repository: AlgoGos
    type: Git
    name: ALGO-GOS
  - repository: AlgoShared
    type: Git
    name: ALGO-SHARED

trigger: none
# - main

variables:
  - group: AZURE_VARS

pool:
  vmImage: windows-latest

jobs:
  - job: buildApplication
    displayName: Build Application
    steps:
      - checkout: self
        submodules: true
      
      - task: PowerShell@2
        inputs:
         targetType: inline
         script: |
           # use $env:AZURE_CLIENT_ID for client id
           # use $env:AZURE_SECRET_KEY for secret key
           # use $env:AZURE_TENANT_ID for tenant id
        env:
          AZURE_CLIENT_ID: $(CLIENT_ID)
          AZURE_SECRET_KEY: $(SECRET_KEY)
          AZURE_TENANT_ID: $(TENANT_ID)

      # Frontend
      # -------

      - script: |
          (cd src/renderer && npm install && npm run build)
        displayName: 'Build the renderer'

      # Application
      # -------

      - script: npm install
        displayName: NPM install App

      # NWS - WIN

      - script: |
          node tools/activate-algo.js algo-uscadi
          npx electron-forge make --arch=x64 --platform=win32
        displayName: "Build app-nws-win"
      
      - task: TrustedSigning@0
        displayName: "Code sign the application"
        inputs:
          AzureTenantID: $(TENANT_ID)
          AzureClientID: $(CLIENT_ID)
          AzureClientSecret: $(CLIENT_SECRET)
          Endpoint: $(ENDPOINT)
          CodeSigningAccountName: $(CODE_SIGNING_ACCOUNT_NAME)
          CertificateProfileName: $(CERTIFICATE_PROFILE_NAME)
          
          TimestampRfc3161: 'http://timestamp.acs.microsoft.com'
          TimestampDigest: SHA256
          
          FilesFolder: $(System.DefaultWorkingDirectory)/out/make/squirrel.windows/x64
          FilesFolderRecurse: true
          FileDigest: SHA256
          FilesFolderFilter: exe

          ExcludeAzureCliCredential: true
          ExcludeAzurePowerShellCredential: true
          ExcludeInteractiveBrowserCredential: true
          ExcludeManagedIdentityCredential: true
          ExcludeSharedTokenCacheCredential: true
          ExcludeVisualStudioCodeCredential: true
          ExcludeVisualStudioCredential: true
          ExcludeEnvironmentCredential: false

      # Publishing should either be to Azure Blob storage (to be set up) or via Releases
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(System.DefaultWorkingDirectory)/out/make/squirrel.windows/x64
          artifactName: app-nws-win
        displayName: Publish app-nws-win
        enabled: true

      # GOS - WIN

      - script: |
          node tools/activate-algo.js algo-gos
          npx electron-forge make --arch=x64 --platform=win32
        displayName: "Build app-gos-win"
      
      - task: TrustedSigning@0
        displayName: "Code sign the application"
        inputs:
          AzureTenantID: $(TENANT_ID)
          AzureClientID: $(CLIENT_ID)
          AzureClientSecret: $(CLIENT_SECRET)
          Endpoint: $(ENDPOINT)
          CodeSigningAccountName: $(CODE_SIGNING_ACCOUNT_NAME)
          CertificateProfileName: $(CERTIFICATE_PROFILE_NAME)
          
          TimestampRfc3161: 'http://timestamp.acs.microsoft.com'
          TimestampDigest: SHA256
          
          FilesFolder: $(System.DefaultWorkingDirectory)/out/make/squirrel.windows/x64
          FilesFolderRecurse: true
          FileDigest: SHA256
          FilesFolderFilter: exe
  
          ExcludeAzureCliCredential: true
          ExcludeAzurePowerShellCredential: true
          ExcludeInteractiveBrowserCredential: true
          ExcludeManagedIdentityCredential: true
          ExcludeSharedTokenCacheCredential: true
          ExcludeVisualStudioCodeCredential: true
          ExcludeVisualStudioCredential: true
          ExcludeEnvironmentCredential: false

      # Publishing should either be to Azure Blob storage (to be set up) or via Releases
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(System.DefaultWorkingDirectory)/out/make/squirrel.windows/x64
          artifactName: app-gos-win
        displayName: Publish app-gos-win
        enabled: true


      - script: ls -laR out/
        displayName: Lets look at the output

    uses:
      repositories:
      - AlgoNws
      - AlgoGos
      - AlgoShared

