// this is the directly loaded data as presented by the USCADI preloader
export const INPUT_DATA = {
    "sheets": [
        {
            "name": "Sheet 1",
            "data": [                {
                    "individual_reference": "432942656916",
                    "first_name": "هايل",
                    "last_name": "عجرمة (العجارمة)",
                    "father_first_name": "رائد",
                    "father_last_name": "صيداوي",
                    "mother_first_name": "اعتماد",
                    "dob_year": "1994",
                    "document_type": "LOCAL_COUNCIL_CARD",
                    "document_id": "3702448519.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "92897",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "385914605184",
                    "first_name": "جدير",
                    "last_name": "تميم",
                    "father_first_name": "رائد",
                    "father_last_name": "صيداوي",
                    "mother_first_name": "اعتماد",
                    "dob_year": "1982",
                    "document_type": "LOCAL_COUNCIL_CARD",
                    "document_id": "328519427555.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "98492",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "173862970901",
                    "first_name": "ناجح",
                    "last_name": "حاشد",
                    "father_first_name": "رائد",
                    "father_last_name": "صيداوي",
                    "mother_first_name": "اعتماد",
                    "dob_year": "1975",
                    "document_type": "PERSONAL_ID",
                    "document_id": "566777442586.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "97661",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "545986759749",
                    "first_name": "ميار",
                    "last_name": "الحداء",
                    "father_first_name": "رائد",
                    "father_last_name": "صيداوي",
                    "mother_first_name": "اعتماد",
                    "dob_year": "1978",
                    "document_type": "PERSONAL_ID",
                    "document_id": "544743529433.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "85284",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "565522169020",
                    "first_name": "طيّب",
                    "last_name": "قحطان",
                    "father_first_name": "رائد",
                    "father_last_name": "صيداوي",
                    "mother_first_name": "اعتماد",
                    "dob_year": "2002",
                    "document_type": "LOCAL_COUNCIL_CARD",
                    "document_id": "715616143121.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "58872",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "598932087410",
                    "first_name": "هلال",
                    "last_name": "البخاري",
                    "father_first_name": "مهنّد",
                    "father_last_name": "بارق",
                    "mother_first_name": "جالا",
                    "dob_year": "1977",
                    "document_type": "PERSONAL_ID",
                    "document_id": "684748761566.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "93273",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "980992916979",
                    "first_name": "روبين",
                    "last_name": "بنو الحارث بن كعب",
                    "father_first_name": "مهنّد",
                    "father_last_name": "بارق",
                    "mother_first_name": "جالا",
                    "dob_year": "2006",
                    "document_type": "LOCAL_COUNCIL_CARD",
                    "document_id": "326761296326.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "50110",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "439209350958",
                    "first_name": "عدوي",
                    "last_name": "إياد",
                    "father_first_name": "مهنّد",
                    "father_last_name": "بارق",
                    "mother_first_name": "جالا",
                    "dob_year": "1979",
                    "document_type": "NATIONAL_ID",
                    "document_id": "704779968243.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "76633",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "833074092693",
                    "first_name": "غزوان",
                    "last_name": "الحواش",
                    "father_first_name": "مهنّد",
                    "father_last_name": "بارق",
                    "mother_first_name": "جالا",
                    "dob_year": "19801",
                    "document_type": "LOCAL_COUNCIL_CARD",
                    "document_id": "867570160444.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "84279",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "896857677336",
                    "first_name": "فرزدق",
                    "last_name": "الطحان",
                    "father_first_name": "مهنّد",
                    "father_last_name": "بارق",
                    "mother_first_name": "جالا",
                    "dob_year": "2009",
                    "document_type": "NATIONAL_ID",
                    "document_id": "121080246401.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "61316",
                    "start": "20240401",
                    "end": "20240701"
                },

                {
                    "individual_reference": "432942656916",
                    "first_name": "هايل",
                    "last_name": "عجرمة (العجارمة)",
                    "father_first_name": "رائد",
                    "father_last_name": "صيداوي",
                    "mother_first_name": "اعتماد",
                    "dob_year": "1994",
                    "document_type": "LOCAL_COUNCIL_CARD",
                    "document_id": "3702448519.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "92897",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "385914605184",
                    "first_name": "جدير",
                    "last_name": "تميم",
                    "father_first_name": "رائد",
                    "father_last_name": "صيداوي",
                    "mother_first_name": "اعتماد",
                    "dob_year": "1982",
                    "document_type": "LOCAL_COUNCIL_CARD",
                    "document_id": "328519427555.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "98492",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "173862970901",
                    "first_name": "ناجح",
                    "last_name": "حاشد",
                    "father_first_name": "رائد",
                    "father_last_name": "صيداوي",
                    "mother_first_name": "اعتماد",
                    "dob_year": "1975",
                    "document_type": "PERSONAL_ID",
                    "document_id": "566777442586.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "97661",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "545986759749",
                    "first_name": "ميار",
                    "last_name": "الحداء",
                    "father_first_name": "رائد",
                    "father_last_name": "صيداوي",
                    "mother_first_name": "اعتماد",
                    "dob_year": "1978",
                    "document_type": "PERSONAL_ID",
                    "document_id": "544743529433.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "85284",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "565522169020",
                    "first_name": "طيّب",
                    "last_name": "قحطان",
                    "father_first_name": "رائد",
                    "father_last_name": "صيداوي",
                    "mother_first_name": "اعتماد",
                    "dob_year": "2002",
                    "document_type": "LOCAL_COUNCIL_CARD",
                    "document_id": "715616143121.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "58872",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "598932087410",
                    "first_name": "هلال",
                    "last_name": "البخاري",
                    "father_first_name": "مهنّد",
                    "father_last_name": "بارق",
                    "mother_first_name": "جالا",
                    "dob_year": "1977",
                    "document_type": "PERSONAL_ID",
                    "document_id": "684748761566.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "93273",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "980992916979",
                    "first_name": "روبين",
                    "last_name": "بنو الحارث بن كعب",
                    "father_first_name": "مهنّد",
                    "father_last_name": "بارق",
                    "mother_first_name": "جالا",
                    "dob_year": "2006",
                    "document_type": "LOCAL_COUNCIL_CARD",
                    "document_id": "326761296326.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "50110",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "439209350958",
                    "first_name": "عدوي",
                    "last_name": "إياد",
                    "father_first_name": "مهنّد",
                    "father_last_name": "بارق",
                    "mother_first_name": "جالا",
                    "dob_year": "1979",
                    "document_type": "NATIONAL_ID",
                    "document_id": "704779968243.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "76633",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "833074092693",
                    "first_name": "غزوان",
                    "last_name": "الحواش",
                    "father_first_name": "مهنّد",
                    "father_last_name": "بارق",
                    "mother_first_name": "جالا",
                    "dob_year": "19801",
                    "document_type": "LOCAL_COUNCIL_CARD",
                    "document_id": "867570160444.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "84279",
                    "start": "20240401",
                    "end": "20240701"
                },
                {
                    "individual_reference": "896857677336",
                    "first_name": "فرزدق",
                    "last_name": "الطحان",
                    "father_first_name": "مهنّد",
                    "father_last_name": "بارق",
                    "mother_first_name": "جالا",
                    "dob_year": "2009",
                    "document_type": "NATIONAL_ID",
                    "document_id": "121080246401.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "61316",
                    "start": "20240401",
                    "end": "20240701"
                }
            ]
        }
    ]
}


export const VALIDATION_RESULT = [
    {
        "sheet": "Sheet 1",
        "ok": false,
        // "results": [
        //     {
        //         "row": {
        //             "individual_reference": "432942656916",
        //             "first_name": "هايل",
        //             "last_name": "عجرمة (العجارمة)",
        //             "father_first_name": "رائد",
        //             "father_last_name": "صيداوي",
        //             "mother_first_name": "اعتماد",
        //             "dob_year": "1994",
        //             "document_type": "LOCAL_COUNCIL_CARD",
        //             "document_id": "3702448519.0",
        //             "organization": "ORG1",
        //             "category": "CASH-MPA",
        //             "currency": "USD",
        //             "amount": "92897",
        //             "start": "20240401",
        //             "end": "20240701"
        //         },
        //         "ok": true,
        //         "errors": []
        //     },
        //     {
        //         "row": {
        //             "individual_reference": "385914605184",
        //             "first_name": "جدير",
        //             "last_name": "تميم",
        //             "father_first_name": "رائد",
        //             "father_last_name": "صيداوي",
        //             "mother_first_name": "اعتماد",
        //             "dob_year": "1982",
        //             "document_type": "LOCAL_COUNCIL_CARD",
        //             "document_id": "328519427555.0",
        //             "organization": "ORG1",
        //             "category": "CASH-MPA",
        //             "currency": "USD",
        //             "amount": "98492",
        //             "start": "20240401",
        //             "end": "20240701"
        //         },
        //         "ok": true,
        //         "errors": []
        //     },
        //     {
        //         "row": {
        //             "individual_reference": "173862970901",
        //             "first_name": "ناجح",
        //             "last_name": "حاشد",
        //             "father_first_name": "رائد",
        //             "father_last_name": "صيداوي",
        //             "mother_first_name": "اعتماد",
        //             "dob_year": "1975",
        //             "document_type": "PERSONAL_ID",
        //             "document_id": "566777442586.0",
        //             "organization": "ORG1",
        //             "category": "CASH-MPA",
        //             "currency": "USD",
        //             "amount": "97661",
        //             "start": "20240401",
        //             "end": "20240701"
        //         },
        //         "ok": true,
        //         "errors": []
        //     },
        //     {
        //         "row": {
        //             "individual_reference": "545986759749",
        //             "first_name": "ميار",
        //             "last_name": "الحداء",
        //             "father_first_name": "رائد",
        //             "father_last_name": "صيداوي",
        //             "mother_first_name": "اعتماد",
        //             "dob_year": "1978",
        //             "document_type": "PERSONAL_ID",
        //             "document_id": "544743529433.0",
        //             "organization": "ORG1",
        //             "category": "CASH-MPA",
        //             "currency": "USD",
        //             "amount": "85284",
        //             "start": "20240401",
        //             "end": "20240701"
        //         },
        //         "ok": true,
        //         "errors": []
        //     },
        //     {
        //         "row": {
        //             "individual_reference": "565522169020",
        //             "first_name": "طيّب",
        //             "last_name": "قحطان",
        //             "father_first_name": "رائد",
        //             "father_last_name": "صيداوي",
        //             "mother_first_name": "اعتماد",
        //             "dob_year": "2002",
        //             "document_type": "LOCAL_COUNCIL_CARD",
        //             "document_id": "715616143121.0",
        //             "organization": "ORG1",
        //             "category": "CASH-MPA",
        //             "currency": "USD",
        //             "amount": "58872",
        //             "start": "20240401",
        //             "end": "20240701"
        //         },
        //         "ok": true,
        //         "errors": []
        //     },
        //     {
        //         "row": {
        //             "individual_reference": "598932087410",
        //             "first_name": "هلال",
        //             "last_name": "البخاري",
        //             "father_first_name": "مهنّد",
        //             "father_last_name": "بارق",
        //             "mother_first_name": "جالا",
        //             "dob_year": "1977",
        //             "document_type": "PERSONAL_ID",
        //             "document_id": "684748761566.0",
        //             "organization": "ORG1",
        //             "category": "CASH-MPA",
        //             "currency": "USD",
        //             "amount": "93273",
        //             "start": "20240401",
        //             "end": "20240701"
        //         },
        //         "ok": true,
        //         "errors": []
        //     },
        //     {
        //         "row": {
        //             "individual_reference": "980992916979",
        //             "first_name": "روبين",
        //             "last_name": "بنو الحارث بن كعب",
        //             "father_first_name": "مهنّد",
        //             "father_last_name": "بارق",
        //             "mother_first_name": "جالا",
        //             "dob_year": "2006",
        //             "document_type": "LOCAL_COUNCIL_CARD",
        //             "document_id": "326761296326.0",
        //             "organization": "ORG1",
        //             "category": "CASH-MPA",
        //             "currency": "USD",
        //             "amount": "50110",
        //             "start": "20240401",
        //             "end": "20240701"
        //         },
        //         "ok": true,
        //         "errors": []
        //     },
        //     {
        //         "row": {
        //             "individual_reference": "439209350958",
        //             "first_name": "عدوي",
        //             "last_name": "إياد",
        //             "father_first_name": "مهنّد",
        //             "father_last_name": "بارق",
        //             "mother_first_name": "جالا",
        //             "dob_year": "1979",
        //             "document_type": "NATIONAL_ID",
        //             "document_id": "704779968243.0",
        //             "organization": "ORG1",
        //             "category": "CASH-MPA",
        //             "currency": "USD",
        //             "amount": "76633",
        //             "start": "20240401",
        //             "end": "20240701"
        //         },
        //         "ok": false,
        //         "errors": [
        //             {
        //                 "column": "document_type",
        //                 "errors": [
        //                     {
        //                         "kind": "options",
        //                         "msg": "not good"
        //                     }
        //                 ]
        //             }
        //         ]
        //     },
        //     {
        //         "row": {
        //             "individual_reference": "833074092693",
        //             "first_name": "غزوان",
        //             "last_name": "الحواش",
        //             "father_first_name": "مهنّد",
        //             "father_last_name": "بارق",
        //             "mother_first_name": "جالا",
        //             "dob_year": "19801",
        //             "document_type": "LOCAL_COUNCIL_CARD",
        //             "document_id": "867570160444.0",
        //             "organization": "ORG1",
        //             "category": "CASH-MPA",
        //             "currency": "USD",
        //             "amount": "84279",
        //             "start": "20240401",
        //             "end": "20240701"
        //         },
        //         "ok": false,
        //         "errors": [
        //             {
        //                 "column": "dob_year",
        //                 "errors": [
        //                     {
        //                         "kind": "min_value",
        //                         "msg": "must be at most 2024"
        //                     }
        //                 ]
        //             }
        //         ]
        //     },
        //     {
        //         "row": {
        //             "individual_reference": "896857677336",
        //             "first_name": "فرزدق",
        //             "last_name": "الطحان",
        //             "father_first_name": "مهنّد",
        //             "father_last_name": "بارق",
        //             "mother_first_name": "جالا",
        //             "dob_year": "2009",
        //             "document_type": "NATIONAL_ID",
        //             "document_id": "121080246401.0",
        //             "organization": "ORG1",
        //             "category": "CASH-MPA",
        //             "currency": "USD",
        //             "amount": "61316",
        //             "start": "20240401",
        //             "end": "20240701"
        //         },
        //         "ok": false,
        //         "errors": [
        //             {
        //                 "column": "document_type",
        //                 "errors": [
        //                     {
        //                         "kind": "options",
        //                         "msg": "not good"
        //                     }
        //                 ]
        //             }
        //         ]
        //     }
        // ]
    }
];


export const OUTPUT_DATA = {
    "sheets": [
        {
            "name": "Sheet 1",
            "data": [
                {
                    "individual_reference": "432942656916",
                    "first_name": "هايل",
                    "last_name": "عجرمة (العجارمة)",
                    "father_first_name": "رائد",
                    "father_last_name": "صيداوي",
                    "mother_first_name": "اعتماد",
                    "dob_year": "1994",
                    "document_type": "LOCAL_COUNCIL_CARD",
                    "document_id": "3702448519.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "92897",
                    "start": "20240401",
                    "end": "20240701",
                    "USCADI": "WK4XUQO2ZNQBTJVZQYUDOYEDH75SIQQYXEBWIRRK5AO5J47U2A3Q====",
                    "document_hash": "JKKI2WDCNKLURCVG2WBXCMXROUPHYWR7SEBCYN5RRRIPIKL4LZCA====",
                    "USCADI_src": "1994HLAJRMPLJRMPRKTSTATMTH4000A2654R6300S2300A3530",
                    "document_hash_src": "LOCAL_COUNCIL_CARD3702448519.0"
                },
                {
                    "individual_reference": "385914605184",
                    "first_name": "جدير",
                    "last_name": "تميم",
                    "father_first_name": "رائد",
                    "father_last_name": "صيداوي",
                    "mother_first_name": "اعتماد",
                    "dob_year": "1982",
                    "document_type": "LOCAL_COUNCIL_CARD",
                    "document_id": "328519427555.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "98492",
                    "start": "20240401",
                    "end": "20240701",
                    "USCADI": "32UVDLVGQF4XIQZA4QU3ORCWF7M74VFX67N7SP2YMTQFY2FUAHUA====",
                    "document_hash": "6LGSCF36AXOFXYQI4Y2NN7QWIKGO7DUJG75USIH2DSJXVLBSOL3A====",
                    "USCADI_src": "1982JTRTMMRKTSTATMTJ2360T3550R6300S2300A3530",
                    "document_hash_src": "LOCAL_COUNCIL_CARD328519427555.0"
                },
                {
                    "individual_reference": "173862970901",
                    "first_name": "ناجح",
                    "last_name": "حاشد",
                    "father_first_name": "رائد",
                    "father_last_name": "صيداوي",
                    "mother_first_name": "اعتماد",
                    "dob_year": "1975",
                    "document_type": "PERSONAL_ID",
                    "document_id": "566777442586.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "97661",
                    "start": "20240401",
                    "end": "20240701",
                    "USCADI": "SSA3NLQG65LLPZKJR3E262EL5WYP7DAREIQ7BH4EHQN7VOYD4EPQ====",
                    "document_hash": "K2NUH2CLFQ3DTMM4GLFAFK35FB4JB4PH7JG4Z6OFG6PLPJO3KAHQ====",
                    "USCADI_src": "1975NJHKTRKTSTATMTN5200H2300R6300S2300A3530",
                    "document_hash_src": "PERSONAL_ID566777442586.0"
                },
                {
                    "individual_reference": "545986759749",
                    "first_name": "ميار",
                    "last_name": "الحداء",
                    "father_first_name": "رائد",
                    "father_last_name": "صيداوي",
                    "mother_first_name": "اعتماد",
                    "dob_year": "1978",
                    "document_type": "PERSONAL_ID",
                    "document_id": "544743529433.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "85284",
                    "start": "20240401",
                    "end": "20240701",
                    "USCADI": "B6IQSOAOIMPHQ2I4JO2H2SR66K5CE4GLRMXBFKRZJ3Z2GHTHDV6A====",
                    "document_hash": "77MP6EXRROC63KSM4XJLI7CEG3JZIS7OKJA6Z6BSSBCKOBIMXGNQ====",
                    "USCADI_src": "1978MRALTKRKTSTATMTM5600A4300R6300S2300A3530",
                    "document_hash_src": "PERSONAL_ID544743529433.0"
                },
                {
                    "individual_reference": "565522169020",
                    "first_name": "طيّب",
                    "last_name": "قحطان",
                    "father_first_name": "رائد",
                    "father_last_name": "صيداوي",
                    "mother_first_name": "اعتماد",
                    "dob_year": "2002",
                    "document_type": "LOCAL_COUNCIL_CARD",
                    "document_id": "715616143121.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "58872",
                    "start": "20240401",
                    "end": "20240701",
                    "USCADI": "ET6VNOV5IDLTTMIVABACZO2X6Z3BIDLYDID2LSCNSXERORFTWEIA====",
                    "document_hash": "6KPSWDHNPM7RF3AUNPUGX7BHJSEASV3F26LSH65UFB3UBZKJTK4A====",
                    "USCADI_src": "2002TPKTNRKTSTATMTT3100Q2350R6300S2300A3530",
                    "document_hash_src": "LOCAL_COUNCIL_CARD715616143121.0"
                },
                {
                    "individual_reference": "598932087410",
                    "first_name": "هلال",
                    "last_name": "البخاري",
                    "father_first_name": "مهنّد",
                    "father_last_name": "بارق",
                    "mother_first_name": "جالا",
                    "dob_year": "1977",
                    "document_type": "PERSONAL_ID",
                    "document_id": "684748761566.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "93273",
                    "start": "20240401",
                    "end": "20240701",
                    "USCADI": "Q7VFN5APIUODTFP7H6C5A4WRGKN4EKR35AJXHSH54ZEXPL3UYJ6Q====",
                    "document_hash": "HHVAX4KBOSH45WOEFZVLZLJBPIVH4WM7BKWYPI75YHCAUOCAYC5A====",
                    "USCADI_src": "1977LLALPKRMNTPRKJLH4400A4126M5530B1620J2400",
                    "document_hash_src": "PERSONAL_ID684748761566.0"
                },
                {
                    "individual_reference": "980992916979",
                    "first_name": "روبين",
                    "last_name": "بنو الحارث بن كعب",
                    "father_first_name": "مهنّد",
                    "father_last_name": "بارق",
                    "mother_first_name": "جالا",
                    "dob_year": "2006",
                    "document_type": "LOCAL_COUNCIL_CARD",
                    "document_id": "326761296326.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "50110",
                    "start": "20240401",
                    "end": "20240701",
                    "USCADI": "NXOYHJIQ37YWZUXDEUKWHHGGLYR2XQPAWKNTPGG72HYBOUPEVVTQ====",
                    "document_hash": "XJJZQNPJW3CNF6W664E7O7VVM7QDK7OTMLYHE3HW22TFG2E277BQ====",
                    "USCADI_src": "2006RPNPNLRFPNKPMNTPRKJLR6150B1546M5530B1620J2400",
                    "document_hash_src": "LOCAL_COUNCIL_CARD326761296326.0"
                },
                {
                    "individual_reference": "439209350958",
                    "first_name": "عدوي",
                    "last_name": "إياد",
                    "father_first_name": "مهنّد",
                    "father_last_name": "بارق",
                    "mother_first_name": "جالا",
                    "dob_year": "1979",
                    "document_type": "NATIONAL_ID",
                    "document_id": "704779968243.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "76633",
                    "start": "20240401",
                    "end": "20240701",
                    "USCADI": "E3SJXO62KJ7C7WJJJTAVSVHMXNQJPEXJDTDJAY2ZZZ7KHH4CGTJA====",
                    "document_hash": "MG5BKMNSRJZEZVQSVMTH2GH7LXRQ3VKBXQWU2KC573T4CFO4PWZA====",
                    "USCADI_src": "1979ATATMNTPRKJLA300030000M5530B1620J2400",
                    "document_hash_src": "NATIONAL_ID704779968243.0"
                },
                {
                    "individual_reference": "833074092693",
                    "first_name": "غزوان",
                    "last_name": "الحواش",
                    "father_first_name": "مهنّد",
                    "father_last_name": "بارق",
                    "mother_first_name": "جالا",
                    "dob_year": "19801",
                    "document_type": "LOCAL_COUNCIL_CARD",
                    "document_id": "867570160444.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "84279",
                    "start": "20240401",
                    "end": "20240701",
                    "USCADI": "4QYIX3SKUOL3JIAX2BRJ3RNA7T7ZIRATKISK4HXWO47UOTDKLIFQ====",
                    "document_hash": "BFWJ4XYRCJAHBO3PUF5CH465XTPKMHADREIZFEKDH2OYYCK6RNPA====",
                    "USCADI_src": "19801KSNALKMNTPRKJLG2500A4200M5530B1620J2400",
                    "document_hash_src": "LOCAL_COUNCIL_CARD867570160444.0"
                },
                {
                    "individual_reference": "896857677336",
                    "first_name": "فرزدق",
                    "last_name": "الطحان",
                    "father_first_name": "مهنّد",
                    "father_last_name": "بارق",
                    "mother_first_name": "جالا",
                    "dob_year": "2009",
                    "document_type": "NATIONAL_ID",
                    "document_id": "121080246401.0",
                    "organization": "ORG1",
                    "category": "CASH-MPA",
                    "currency": "USD",
                    "amount": "61316",
                    "start": "20240401",
                    "end": "20240701",
                    "USCADI": "7VOZLABSTP3EDNSWWGRWQBMZZG7ZU3YXHCKFRE43WGRFDI4D5TRA====",
                    "document_hash": "KA24JS2KDJIXKD6OZCTK7FJ7VNEWGAKU4UUQAXCCAPHEXAHQ3MPQ====",
                    "USCADI_src": "2009FRSTKAL0NMNTPRKJLF1623A4350M5530B1620J2400",
                    "document_hash_src": "NATIONAL_ID121080246401.0"
                }
            ]
        }
    ]
};