[meta]
# The application binary must support this region to allow the use of this configuration file
region="GOS"

# The version of the configuration file
version="0.0.9"

# HTML to display as Terms And Conditions
terms_and_conditions="""
<p>Lorem ipsum <a href="https://wfp.org" target="_blank">dolor</a> sit amet, <b>consectetur adipiscing</b> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

<p><i>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</i> fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>Lorem ipsum <a href="https://wfp.org" target="_blank">dolor</a> sit amet, <b>consectetur adipiscing</b> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

<p><i>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</i> fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>Lorem ipsum <a href="https://wfp.org" target="_blank">dolor</a> sit amet, <b>consectetur adipiscing</b> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

<p><i>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</i> fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>Lorem ipsum <a href="https://wfp.org" target="_blank">dolor</a> sit amet, <b>consectetur adipiscing</b> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

<p><i>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</i> fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>Lorem ipsum <a href="https://wfp.org" target="_blank">dolor</a> sit amet, <b>consectetur adipiscing</b> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

<p><i>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</i> fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>Lorem ipsum <a href="https://wfp.org" target="_blank">dolor</a> sit amet, <b>consectetur adipiscing</b> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

<p><i>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</i> fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

"""

[messages]

error_in_config="""

<p>The application encountered an error while attempting to load a configuration file.</p>

<p>Please contanct WFP support at <a href="mailto:some.email@wfp.org">some.email@wfp.org</a></p>
"""

error_in_salt="""
<p>The application encountered an error while attempting to load your individual salt file.</p>

<p>Please contanct WFP support at <a href="mailto:some.email@wfp.org">some.email@wfp.org</a></p>
"""

[source]
columns = [
    { name = "National ID", alias = "national_id" },
    { name = "Organization", alias = "organization" },
    { name = "Category", alias = "category" },
    { name = "Currency", alias = "currency" },
    { name = "Amount", alias = "amount" },
    { name = "Start (yyyyMMdd)", alias = "start" },
    { name = "End (yyyyMMdd)", alias = "end" },
]

[validations]

"*" = [
    { op = "max_field_length", value = 200 },
    { op = "field_type", value = "str" },
]

# biographic columns
national_id = [
    { op = "regex_match", value = '(\d{11})' }
]

# assistance columns
organization = [
    { op = "regex_match", value = 'ORG1' },
]

category = [
    { op = "regex_match", value = '(\S{6,12})' },
    { op = "options", value = [ "CASH-MPA", "CASH-RENT" ] }
]

currency = [
    { op = "regex_match", value = 'USD' }
]

amount = [
    { op = "min_value", value = 1 },
    { op = "max_value", value = 1000 },
]

start = [
    { op = "regex_match", value = '((?:19|20)\d{2}(?:0[1-9]|1[012])(?:0[1-9]|[12]\d|3[01]))' }, # yyyyMMdd
    { op = "date_diff", value = "+3M"},
    { op = "date_diff", value = "-12M"}
]

end = [
    { op = "regex_match", value = '((?:19|20)\d{2}(?:0[1-9]|1[012])(?:0[1-9]|[12]\d|3[01]))' }, # yyyyMMdd
    { op = "date_diff", value = "+3M"},
    { op = "date_diff", value = "-12M"},
    { op = "date_field_diff", target = "start", value="-12M"},
]


[algorithm]

[algorithm.columns]
to_translate = [
    # "first_name",
    # "last_name",
    # "father_first_name",
    # "father_last_name",
    # "mother_first_name",
]
static = [
    "national_id",
]
reference = [
    # "document_type",
    # "document_id"
]

[algorithm.hash]
strategy = "SHA256" # SHA256 | SCRYPT | ARGON2
num_iterations = 512
parallelism = 1
block_size = 8
size = 32

[algorithm.salt]
source = "FILE" # STRING | FILE
# The regular expression to validate the salt file
validator_regex = "-----BEGIN PGP PUBLIC KEY BLOCK-----[A-Za-z0-9+/=\\s]+-----END PGP PUBLIC KEY BLOCK-----"


[algorithm.salt.value]
# $APPDATA can be used to substitute the application data directory
win32 = "./test_files/public_system.asc"
# $HOME can be used to substitute the users home directory
darwin = "$APPDATA/CommonIDTool/public_system.asc"


[destination]
columns = [
    { name = "Hashed ID", alias = "hashed_id" },
    { name = "Organization", alias = "organization" },
    { name = "Category", alias = "category" },
    { name = "Currency", alias = "currency" },
    { name = "Amount", alias = "amount" },
    { name = "Start (yyyyMMdd)", alias = "start" },
    { name = "End (yyyyMMdd)", alias = "end" },
]
# The postfix of the output file. Anything inside double curly braces
# will be treated as a date format string.
# FORMATTING TOKEN GUIDE: https://date-fns.org/v3.6.0/docs/lightFormat
postfix = "-OUTPUT-GOS-0.0.9-{{yyyy-MM-dd--HH-mm-ss}}"

[destination_map]
columns = [
    { name = "National ID", alias = "national_id" },
    { name = "Hashed ID", alias = "hashed_id" }
]
postfix = "-MAPPING-GOS-0.0.9-{{yyyy-MM-dd--HH-mm-ss}}"

[destination_errors]
columns = [
    { name = "Errors", alias = "errors" },
    { name = "National ID", alias = "national_id" },
    { name = "Organization", alias = "organization" },
    { name = "Category", alias = "category" },
    { name = "Currency", alias = "currency" },
    { name = "Amount", alias = "amount" },
    { name = "Start (yyyyMMdd)", alias = "start" },
    { name = "End (yyyyMMdd)", alias = "end" },
]
postfix = "-ERRORS-GOS-0.0.9-{{yyyy-MM-dd--HH-mm-ss}}"


[signature]
config_signature="67c0f04047149df5e126f443e454c7f9"