[meta]
# The application binary must support this region to allow the use of this configuration file
region="NWS"

# The version of the configuration file
version="1.0.8"

# HTML to display as Terms And Conditions
terms_and_conditions="""
<p>Lorem ipsum <a href="https://wfp.org" target="_blank">dolor</a> sit amet, <b>consectetur adipiscing</b> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

<p><i>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</i> fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>Lorem ipsum <a href="https://wfp.org" target="_blank">dolor</a> sit amet, <b>consectetur adipiscing</b> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

<p><i>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</i> fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>Lorem ipsum <a href="https://wfp.org" target="_blank">dolor</a> sit amet, <b>consectetur adipiscing</b> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

<p><i>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</i> fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>Lorem ipsum <a href="https://wfp.org" target="_blank">dolor</a> sit amet, <b>consectetur adipiscing</b> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

<p><i>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</i> fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>Lorem ipsum <a href="https://wfp.org" target="_blank">dolor</a> sit amet, <b>consectetur adipiscing</b> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

<p><i>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</i> fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>Lorem ipsum <a href="https://wfp.org" target="_blank">dolor</a> sit amet, <b>consectetur adipiscing</b> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

<p><i>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu</i> fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

"""

[messages]

error_in_config="""

<p>The application encountered an error while attempting to load a configuration file.</p>

<p>Please contanct WFP support at <a href="mailto:some.email@wfp.org">some.email@wfp.org</a></p>
"""

error_in_salt="""
<p>The application encountered an error while attempting to load your individual salt file.</p>

<p>Please contanct WFP support at <a href="mailto:some.email@wfp.org">some.email@wfp.org</a></p>
"""

[source]
columns = [
    { name = "Individual Reference", alias = "individual_reference" },
    { name = "First Name", alias = "first_name" },
    { name = "Last Name", alias = "last_name" },
    { name = "Father First Name", alias = "father_first_name" },
    { name = "Father Last Name", alias = "father_last_name" },
    { name = "Mother First Name", alias = "mother_first_name" },
    { name = "Year of Birth", alias = "dob_year" },
    { name = "Document Type", alias = "document_type" },
    { name = "Document ID", alias = "document_id" },
    { name = "Organization", alias = "organization" },
    { name = "Category", alias = "category" },
    { name = "Currency", alias = "currency" },
    { name = "Amount", alias = "amount" },
    { name = "Start (yyyyMMdd)", alias = "start" },
    { name = "End (yyyyMMdd)", alias = "end" },
]

[validations]

"*" = [
    { op = "max_field_length", value = 200 },
    { op = "field_type", value = "str" },
]

# biographic columns
individual_reference = [
    { op = "regex_match", value = '(\d{8,14})', message="is not a number with 8-14 digits" } # TBD
]

first_name = [
    # Example message for a language check if needed
    { op = "language_check", value = "Arabic", message="is not Arabic"}
]

last_name = [
    # The default error message for the 'lanaguage_check' is "languge is not <LANGUAGE>"
    # so the default error messages should be enough
    { op = "language_check", value = "Arabic"}
]

father_first_name = [
    { op = "language_check", value = "Arabic"}
]

father_last_name = [
    { op = "language_check", value = "Arabic"}
]

mother_first_name = [
    { op = "language_check", value = "Arabic"}
]


dob_year = [
    # default error message for these validators is "is not less then ..." / "is not greater then ..."
    { op = "min_value", value = 1901 },
    { op = "max_value", value = 2024 },
]

document_type = [
    # default
    { op = "options", value = [ "", "NATIONAL_ID", "PERSONAL_ID", "LOCAL_COUNCIL_CARD" ], message="not good" }
]

document_id = [] # TBD

# assistance columns
organization = [
    { op = "regex_match", value = 'ORG1', message="is not 'ORG1'" },
]

category = [
    { op = "regex_match", value = '(\S{6,12})', message="does not look like a category name" },
    { op = "options", value = [ "CASH-MPA", "CASH-RENT" ] }
]

currency = [
    { op = "regex_match", value = 'USD', message="must be 'USD'" }
]

amount = [
    { op = "min_value", value = 1000 },
    { op = "max_value", value = 100000 },
]

start = [
    { op = "regex_match", value = '((?:19|20)\d{2}(?:0[1-9]|1[012])(?:0[1-9]|[12]\d|3[01]))', message="is in the wrong date format" }, # yyyyMMdd
    { op = "date_diff", value = "+3M"},
    { op = "date_diff", value = "-12M"}
]

end = [
    { op = "regex_match", value = '((?:19|20)\d{2}(?:0[1-9]|1[012])(?:0[1-9]|[12]\d|3[01]))', message="is in the wrong date format"  }, # yyyyMMdd
    { op = "date_diff", value = "+3M"},
    { op = "date_diff", value = "-12M"},
    { op = "date_field_diff", target = "start", value="-12M"},
]


[algorithm]

[algorithm.columns]
to_translate = [
    "first_name",
    "last_name",
    "father_first_name",
    "father_last_name",
    "mother_first_name",
]
static = [
    "dob_year"
]
reference = [
    "document_type",
    "document_id"
]

[algorithm.hash]
strategy = "SHA256" # SHA256 | SCRYPT | ARGON2
num_iterations = 512
parallelism = 1
block_size = 8
size = 32


[algorithm.salt]
source = "FILE" # STRING | FILE
# The regular expression to validate the salt file
validator_regex = "-----BEGIN PGP PUBLIC KEY BLOCK-----[A-Za-z0-9+/=\\s]+-----END PGP PUBLIC KEY BLOCK-----"


[algorithm.salt.value]
# $APPDATA can be used to substitute the application data directory
win32 = "./test_files/public_system.asc"
# $HOME can be used to substitute the users home directory
darwin = "$APPDATA/CommonIDTool/public_system.asc"


[destination]
columns = [
    { name = "USCADI", alias = "USCADI" },
    { name = "USCADI Source", alias = "USCADI_src" },
    { name = "Organization", alias = "organization" },
    { name = "Category", alias = "category" },
    { name = "Currency", alias = "currency" },
    { name = "Amount", alias = "amount" },
    { name = "Start (yyyyMMdd)", alias = "start" },
    { name = "End (yyyyMMdd)", alias = "end" },
    { name = "Document Hash", alias = "document_hash" },
]
# The postfix of the output file. Anything inside double curly braces
# will be treated as a date format string.
# FORMATTING TOKEN GUIDE: https://date-fns.org/v3.6.0/docs/lightFormat
postfix = "-OUTPUT-NWS-1.0.8-{{yyyy-MM-dd--HH-mm-ss}}"

[destination_map]
columns = [
    { name = "Individual Reference", alias = "individual_reference" },
    { name = "USCADI", alias = "USCADI" },
    { name = "Document Hash", alias = "document_hash" },
]
postfix = "-MAPPING-NWS-1.0.8-{{yyyy-MM-dd--HH-mm-ss}}"

[destination_errors]
columns = [
    { name = "Errors", alias = "errors" },
    { name = "Individual Reference", alias = "individual_reference" },
    { name = "First Name", alias = "first_name" },
    { name = "Last Name", alias = "last_name" },
    { name = "Father First Name", alias = "father_first_name" },
    { name = "Father Last Name", alias = "father_last_name" },
    { name = "Mother First Name", alias = "mother_first_name" },
    { name = "Year of Birth", alias = "dob_year" },
    { name = "Document Type", alias = "document_type" },
    { name = "Document ID", alias = "document_id" },
    { name = "Organization", alias = "organization" },
    { name = "Category", alias = "category" },
    { name = "Currency", alias = "currency" },
    { name = "Amount", alias = "amount" },
    { name = "Start (yyyyMMdd)", alias = "start" },
    { name = "End (yyyyMMdd)", alias = "end" },
]
postfix = "-ERRORS-NWS-1.0.8-{{yyyy-MM-dd--HH-mm-ss}}"


[signature]
config_signature="3b685b5ae2554c95ec5b0b3d60295a0f"